--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Mongrel::HttpServer#configure_socket_options
is_singleton: false
name: configure_socket_options
params: ()
visibility: public
