--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: MongrelDbg::configure
is_singleton: true
name: configure
params: (log_dir = File.join("log","mongrel_debug"))
visibility: public
