--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Creates Rails specific configuration options for people to use instead of the base Configurator.
constants: []

full_name: Mongrel::Rails::RailsConfigurator
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: rails
- !ruby/object:RI::MethodSummary 
  name: rails
- !ruby/object:RI::MethodSummary 
  name: reload!
- !ruby/object:RI::MethodSummary 
  name: reload!
- !ruby/object:RI::MethodSummary 
  name: setup_rails_signals
- !ruby/object:RI::MethodSummary 
  name: setup_rails_signals
name: RailsConfigurator
superclass: Mongrel::Configurator
